baseURL = "http://localhost:1313"
languageCode = "en-us"
title = "Badger by Dgraph - The Fastest Key-Value Store in Go"
theme="badger-doc-theme"

[[menu.main]]
  name = "Intro"
  url = "/intro/"
  identifier = "intro"
  weight = 1
